### ISSUE TITLE
Currently the boids sample doesn't seem to work

### ISSUE THREAD

**Issue by cx20** [kainino0x/webgpu-boids#1]
I tried the following sample.
http://kai.graphics/webgpu-boids/

However, at present, it seems that many errors occur and it cannot be displayed on Chrome Canary.
The error is probably due to the fact that the `WebGPU`/`WGSL` specification is not up to date, but I hope this sample will work again.

**Comment by kainino0x** [comment]
Yup, this sample is outdated relative to the spec and implementations. Let me see how quick it would be to fix.

**Comment by kainino0x** [comment]
Updated for latest Chrome in fcbd66a.

Unfortunately this also means it no longer works in Firefox. The previous revision works in Firefox though.

**Comment by cx20** [comment]
Thank you for your prompt support. I have verified that the Chrome Canary sample works. It seems to be working fairly lightly.

![image](https://user-images.githubusercontent.com/1833979/131199651-b9559f73-9a3d-4213-8f5e-b8cc7380eec0.png)

Environment: Windows 10 + GeForce RTX 2060 + Chrome Canary 95
